#define V_TH0  0XFF                 
#define V_TL0  0X9C                  
#define V_TMOD 0X01

#define uint unsigned int
#define uchar unsigned char

extern unsigned int ZKB1;
extern unsigned int ZKB2;
extern unsigned int ZKB3;
extern unsigned int ZKB4;
extern unsigned int count_k; //0.1ms计数
extern unsigned int count_kk; //定时计数 
extern unsigned int count_coin;//硬币数量
extern unsigned int count_bottle;//瓶子数量
extern unsigned char mo_time; //行驶时间
extern unsigned int total_length;	 //计小车走的距离
